---
# Create Objects:

# # --- MongoDB Statefulset: ---
# - name: Create objects from template
#   k8s:
#     state: present
#     definition: "{{ lookup('template', 'templates/mongodb-manifest.yml') }}"

# --- RC APP: ---
- name: Create objects from deployment template
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/rocketchat-manifest.yml') }}"

- name: wait for object to get into ready state
  set_fact:
    rc_dc: "{{ lookup('k8s', kind='dc', namespace=NAMESPACE, label_selector=LABEL) }}"
  until: rc_dc.status.readyReplicas == {{ ROCKETCHAT_REPLICAS }}
  retries: 6
  delay: 10
