---
# Create objects based on input:
- name: Create objects from template - "{{ template }}"
  k8s:
    state: present
    definition: "{{ lookup('template', template) }}"

- name: Wait for "{{ kind }}" object pods to get into ready state
  k8s_info:
    api_version: v1
    kind: "{{ kind }}"
    name: "{{ name }}"
    namespace: "{{ namespace }}"
  register: result
  until: (result.resources[0].status.readyReplicas is defined) and (result.resources[0].status.readyReplicas == ready_status)
  delay: 15
  retries: 20
  