---
# Get list of Objects in a namespace:
- name: Get object by type
  set_fact:
    deployments: "{{ lookup('k8s', kind='dc', namespace=NAMESPACE, label_selector=LABEL) }}"
    statefulsets: "{{ lookup('k8s', kind='StatefulSet', namespace=NAMESPACE, label_selector=LABEL) }}"

- debug: msg="{{ deployments }}"
