apiVersion: v1
data:
  scl_enable.sh: |-
    #!/bin/bash
    source scl_source enable rh-mongodb36
kind: ConfigMap
metadata:
  name: scl-enable
  namespace: "{{ NAMESPACE }}"
  labels:
      name: "{{ MONGODB_SERVICE_NAME }}"
