apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: "{{ APPLICATION_NAME }}"
    name: "{{ APPLICATION_NAME }}"
    namespace: "{{ NAMESPACE }}"
  spec:
    ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: "{{ APPLICATION_NAME }}"
      deploymentConfig: "{{ APPLICATION_NAME }}"
    type: ClusterIP
    SessionAffinity: None
- apiVersion: v1
  kind: Route
  metadata:
    name: "{{ APPLICATION_NAME }}"
    namespace: "{{ NAMESPACE }}"
    annotations:
      description: Route for application's http service.
    labels:
      app: "{{ APPLICATION_NAME }}"
  spec:
    host: "{{ HOSTNAME_HTTPS }}"
    port:
      targetPort: 3000-tcp
    to:
      kind: Service 
      name: "{{ APPLICATION_NAME }}"
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect