---
- hosts: localhost
  gather_facts: no
  connection: local
  vars_files: 
   - vars.yml
  vars:
    APP_LABEL: "app={{ APPLICATION_NAME }}"
    DB_ONLY_LABEL: "name={{ MONGODB_SERVICE_NAME }}"
  tasks:
    - name: Clear start before deployment
      include_tasks: tasks/clear_object.yml
      vars:
        LABEL: "{{ APP_LABEL }}"

    - name: Deploy RC app and MongoDB
      include_tasks: tasks/create_object.yml
