---
- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
   - vars.yml
  vars:
    APP_LABEL: "app={{ APPLICATION_NAME }}"
    DB_ONLY_LABEL: "name={{ MONGODB_SERVICE_NAME }}"
    # mongo operation settings
    ORIGINAL_SS_POD: "{{ MONGODB_SERVICE_NAME }}-0"
  tasks:
    - name: Clear start before deployment
      include_tasks: tasks/clear_object.yml
      vars:
        LABEL: "{{ APP_LABEL }}"

    - name: Deploy MongoDB statefulset
      include_tasks: tasks/create_object.yml
      vars:
        name: "{{ MONGODB_SERVICE_NAME }}"
        kind: StatefulSet
        template: templates/mongodb-manifest.yml
        namespace: "{{ NAMESPACE }}"
        ready_status: "{{ MONGODB_REPLICAS }}"

    # Check for MongoDB syncing status
    - name: Add hosts for MongoDB pods
      add_host:
        name: "{{ ORIGINAL_SS_POD }}"
        groups:
        - mongo_pod
    
    - debug: msg="------------- Switching to kubectl for pod interaction -------------"

# TODO: use inventory instead
# Switch to mongo_pod host for pod interaction
- hosts: mongo_pod
  gather_facts: yes
  connection: kubectl
  tasks:
    - name: Clear start before deployment
      include_tasks: tasks/replica_set_operation.yml

    - debug: msg="------- MongoDB ready, continue with App deployment -------"

# Switch back to localhost
- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
   - vars.yml
  tasks:
    - name: Deploy RC app
      include_tasks: tasks/create_object.yml
      vars:
        name: "{{ APPLICATION_NAME }}"
        kind: dc
        template: templates/rocketchat-manifest.yml
        namespace: "{{ NAMESPACE }}"
        ready_status: "{{ ROCKETCHAT_REPLICAS }}"

    - name: Check application reachable from outside cluster
      uri:
        url: "https://{{ HOSTNAME_HTTPS }}/api/info"
      register: output
      until: output.status == 200
      delay: 15
      retries: 5
    
    - debug: msg="------- RocketChat App ready, continue with channel Creation -------"

    - name: RC settings via API
      include_tasks: tasks/rc_setup.yml

    - name: Switch production app route
      include_tasks: tasks/switch_route.yml
      vars:
        template: templates/rocketchat-route-manifest.yml

    - debug: msg="------- Completed. Available at https://{{ PROD_HOSTNAME_HTTPS }} -------"
