#----- General Settings -----
NAMESPACE: xx
APPLICATION_NAME: rocketchat-maintenance

#----- RocketChat Settings -----
HOSTNAME_HTTPS: xx

# RC image:
ROCKETCHAT_IMAGE_TAG: 3.0
ROCKETCHAT_IMAGE: registry.hub.docker.com/library/rocket.chat

# storage to allocate for file uploads to RocketChat
FILE_UPLOAD_STORAGE_SIZE: 5Gi
SC_FILE_UPLOAD: netapp-file-standard

# Admin access to app
ROCKETCHAT_ADMIN_USER: admin
ROCKETCHAT_ADMIN_PASSWORD: "{{ lookup('password', '/tmp/rc-password length=16 chars=ascii_letters,digits') }}"

# HA HorizontalPodAutoscaler
ROCKETCHAT_REPLICAS: 2
ROCKETCHAT_MIN_HPA: 2
ROCKETCHAT_MAX_HPA: 3

# DevOps resources
MEMORY_REQUEST: 2Gi
MEMORY_LIMIT: 5Gi
CPU_REQUEST: 500m
CPU_LIMIT: 2


#----- MongoDB settings -----
MONGODB_SERVICE_NAME: mongodb-maintenance
# Replica set
MONGODB_REPLICAS: 3

# MongoDB Secret
MONGODB_SECRET_NAME: mongodb-maintenance
MONGODB_REPLICA_NAME: rs0
MONGODB_DATABASE: rocketdb
MONGODB_USER: "{{ lookup('password', '/tmp/mongo-password-0 length=5 chars=ascii_letters,digits') }}"
MONGODB_PASSWORD: "{{ lookup('password', '/tmp/mongo-passwor-1 length=8 chars=ascii_letters,digits') }}"
MONGODB_ADMIN_PASSWORD: "{{ lookup('password', '/tmp/mongo-password-2 length=8 chars=ascii_letters,digits') }}"

# The value of the MongoDB keyfile
# (https://docs.mongodb.com/manual/core/security-internal-authentication/#internal-auth-keyfile)
MONGODB_KEYFILE_VALUE: "{{ lookup('password', '/tmp/mongo-password-3 length=255 chars=ascii_letters,digits') }}"

# MongoDB Image, supported from openshift namespace
MONGODB_IMAGE: docker-registry.default.svc:5000/openshift/mongodb
MONGODB_IMAGE_TAG: 3.6

# DB storage
VOLUME_CAPACITY: 10Gi
SC_MONGO: netapp-block-standard

#----- RC notification settings -----
CHANNLE_NAME: General
MESSAGE: We are currently upgrading production RocketChat instance, this is the temporary chat room for us to communicate with you on the progress.


#----- Database Backup-Restore-Verify settings -----
BACKUP_MONGODB_NAME: mongodb-backup
BACKUP_MONGODB_SCRIPT: backup-restore-verify
MONGODB_SERVICE_PORT: '27017'
# Number of backups to keep
MONGODB_BACKUP_KEEP: 3
BACKUP_MONGODB_REPLICAS: 1

# explain: PVC is a normal PVC as this data does not need to be preserved
# using a dc as this does not need to be run regularly
